/*
 * static_files.c - Embedded static file serving
 *
 * Contains embedded HTML, CSS, and JavaScript for the web dashboard.
 */
#include "static_files.h"
#include <string.h>

/* Embedded index.html */
static const char INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>QMem - Memory Monitor</title>\n"
"    <link rel=\"stylesheet\" href=\"/style.css\">\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <header>\n"
"            <h1>QMem Memory Monitor</h1>\n"
"            <div id=\"status\" class=\"status\">Connecting...</div>\n"
"        </header>\n"
"\n"
"        <section class=\"card\">\n"
"            <h2>System Memory</h2>\n"
"            <div class=\"stat-grid\">\n"
"                <div class=\"stat\">\n"
"                    <span class=\"label\">Usage</span>\n"
"                    <span id=\"usage\" class=\"value\">--</span>\n"
"                </div>\n"
"                <div class=\"stat\">\n"
"                    <span class=\"label\">Available</span>\n"
"                    <span id=\"available\" class=\"value\">--</span>\n"
"                </div>\n"
"                <div class=\"stat\">\n"
"                    <span class=\"label\">Cached</span>\n"
"                    <span id=\"cached\" class=\"value\">--</span>\n"
"                </div>\n"
"                <div class=\"stat\">\n"
"                    <span class=\"label\">Slab</span>\n"
"                    <span id=\"slab\" class=\"value\">--</span>\n"
"                </div>\n"
"            </div>\n"
"            <div class=\"progress-container\">\n"
"                <div id=\"usage-bar\" class=\"progress-bar\"></div>\n"
"            </div>\n"
"        </section>\n"
"\n"
"        <section class=\"card\">\n"
"            <h2>Top RSS Growers</h2>\n"
"            <table id=\"proc-table\">\n"
"                <thead>\n"
"                    <tr>\n"
"                        <th>PID</th>\n"
"                        <th>RSS Delta</th>\n"
"                        <th>RSS</th>\n"
"                        <th>Command</th>\n"
"                    </tr>\n"
"                </thead>\n"
"                <tbody id=\"proc-body\">\n"
"                </tbody>\n"
"            </table>\n"
"        </section>\n"
"\n"
"        <section class=\"card\">\n"
"            <h2>Slab Cache Changes</h2>\n"
"            <table id=\"slab-table\">\n"
"                <thead>\n"
"                    <tr>\n"
"                        <th>Cache</th>\n"
"                        <th>Delta</th>\n"
"                        <th>Current</th>\n"
"                    </tr>\n"
"                </thead>\n"
"                <tbody id=\"slab-body\">\n"
"                </tbody>\n"
"            </table>\n"
"        </section>\n"
"    </div>\n"
"    <script src=\"/app.js\"></script>\n"
"</body>\n"
"</html>\n";

/* Embedded style.css */
static const char STYLE_CSS[] =
":root {\n"
"    --bg-primary: #0d1117;\n"
"    --bg-secondary: #161b22;\n"
"    --bg-tertiary: #21262d;\n"
"    --text-primary: #c9d1d9;\n"
"    --text-secondary: #8b949e;\n"
"    --accent: #58a6ff;\n"
"    --success: #3fb950;\n"
"    --warning: #d29922;\n"
"    --danger: #f85149;\n"
"    --border: #30363d;\n"
"}\n"
"\n"
"* {\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    box-sizing: border-box;\n"
"}\n"
"\n"
"body {\n"
"    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;\n"
"    background: var(--bg-primary);\n"
"    color: var(--text-primary);\n"
"    line-height: 1.5;\n"
"}\n"
"\n"
".container {\n"
"    max-width: 1200px;\n"
"    margin: 0 auto;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"header {\n"
"    display: flex;\n"
"    justify-content: space-between;\n"
"    align-items: center;\n"
"    margin-bottom: 24px;\n"
"    padding-bottom: 16px;\n"
"    border-bottom: 1px solid var(--border);\n"
"}\n"
"\n"
"header h1 {\n"
"    font-size: 24px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
".status {\n"
"    padding: 4px 12px;\n"
"    border-radius: 12px;\n"
"    font-size: 12px;\n"
"    background: var(--bg-tertiary);\n"
"}\n"
"\n"
".status.connected {\n"
"    background: rgba(63, 185, 80, 0.2);\n"
"    color: var(--success);\n"
"}\n"
"\n"
".card {\n"
"    background: var(--bg-secondary);\n"
"    border: 1px solid var(--border);\n"
"    border-radius: 8px;\n"
"    padding: 20px;\n"
"    margin-bottom: 16px;\n"
"}\n"
"\n"
".card h2 {\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    margin-bottom: 16px;\n"
"    color: var(--text-secondary);\n"
"}\n"
"\n"
".stat-grid {\n"
"    display: grid;\n"
"    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));\n"
"    gap: 16px;\n"
"    margin-bottom: 16px;\n"
"}\n"
"\n"
".stat {\n"
"    display: flex;\n"
"    flex-direction: column;\n"
"}\n"
"\n"
".stat .label {\n"
"    font-size: 12px;\n"
"    color: var(--text-secondary);\n"
"    margin-bottom: 4px;\n"
"}\n"
"\n"
".stat .value {\n"
"    font-size: 24px;\n"
"    font-weight: 600;\n"
"    font-variant-numeric: tabular-nums;\n"
"}\n"
"\n"
".progress-container {\n"
"    height: 8px;\n"
"    background: var(--bg-tertiary);\n"
"    border-radius: 4px;\n"
"    overflow: hidden;\n"
"}\n"
"\n"
".progress-bar {\n"
"    height: 100%;\n"
"    background: linear-gradient(90deg, var(--success), var(--warning));\n"
"    transition: width 0.5s ease;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"table {\n"
"    width: 100%;\n"
"    border-collapse: collapse;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"th, td {\n"
"    text-align: left;\n"
"    padding: 8px 12px;\n"
"    border-bottom: 1px solid var(--border);\n"
"}\n"
"\n"
"th {\n"
"    color: var(--text-secondary);\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"tr:hover {\n"
"    background: var(--bg-tertiary);\n"
"}\n"
"\n"
".delta-pos {\n"
"    color: var(--danger);\n"
"}\n"
"\n"
".delta-neg {\n"
"    color: var(--success);\n"
"}\n"
"\n"
".cmd {\n"
"    max-width: 300px;\n"
"    overflow: hidden;\n"
"    text-overflow: ellipsis;\n"
"    white-space: nowrap;\n"
"    color: var(--text-secondary);\n"
"}\n";

/* Embedded app.js */
static const char APP_JS[] =
"(function() {\n"
"    const API_URL = '/api/status';\n"
"    const REFRESH_INTERVAL = 5000;\n"
"\n"
"    function formatBytes(kb) {\n"
"        if (kb >= 1048576) return (kb / 1048576).toFixed(2) + ' GB';\n"
"        if (kb >= 1024) return (kb / 1024).toFixed(2) + ' MB';\n"
"        return kb + ' KB';\n"
"    }\n"
"\n"
"    function formatDelta(kb) {\n"
"        const abs = Math.abs(kb);\n"
"        const str = formatBytes(abs);\n"
"        if (kb > 0) return '+' + str;\n"
"        if (kb < 0) return '-' + str;\n"
"        return '0';\n"
"    }\n"
"\n"
"    function updateUI(data) {\n"
"        const status = document.getElementById('status');\n"
"        status.textContent = 'Connected';\n"
"        status.classList.add('connected');\n"
"\n"
"        // Meminfo\n"
"        const meminfo = data.services?.meminfo;\n"
"        if (meminfo) {\n"
"            document.getElementById('usage').textContent = meminfo.usage_percent?.toFixed(1) + '%';\n"
"            document.getElementById('usage-bar').style.width = meminfo.usage_percent + '%';\n"
"            \n"
"            const mem = meminfo.memory || {};\n"
"            document.getElementById('available').textContent = formatBytes(mem.available_kb?.value || 0);\n"
"            document.getElementById('cached').textContent = formatBytes(mem.cached_kb?.value || 0);\n"
"            \n"
"            const kern = meminfo.kernel || {};\n"
"            document.getElementById('slab').textContent = formatBytes(kern.slab_kb?.value || 0);\n"
"        }\n"
"\n"
"        // Procmem\n"
"        const procmem = data.services?.procmem;\n"
"        const procBody = document.getElementById('proc-body');\n"
"        procBody.innerHTML = '';\n"
"        if (procmem?.top_growers) {\n"
"            procmem.top_growers.forEach(p => {\n"
"                const row = document.createElement('tr');\n"
"                const deltaClass = p.rss_delta_kb > 0 ? 'delta-pos' : 'delta-neg';\n"
"                row.innerHTML = `\n"
"                    <td>${p.pid}</td>\n"
"                    <td class=\"${deltaClass}\">${formatDelta(p.rss_delta_kb)}</td>\n"
"                    <td>${formatBytes(p.rss_kb)}</td>\n"
"                    <td class=\"cmd\">${p.cmd || ''}</td>\n"
"                `;\n"
"                procBody.appendChild(row);\n"
"            });\n"
"        }\n"
"\n"
"        // Slabinfo\n"
"        const slabinfo = data.services?.slabinfo;\n"
"        const slabBody = document.getElementById('slab-body');\n"
"        slabBody.innerHTML = '';\n"
"        if (slabinfo?.top_growers) {\n"
"            slabinfo.top_growers.forEach(s => {\n"
"                const row = document.createElement('tr');\n"
"                row.innerHTML = `\n"
"                    <td>${s.name}</td>\n"
"                    <td class=\"delta-pos\">${formatDelta(Math.floor(s.delta_bytes / 1024))}</td>\n"
"                    <td>${formatBytes(Math.floor(s.size_bytes / 1024))}</td>\n"
"                `;\n"
"                slabBody.appendChild(row);\n"
"            });\n"
"        }\n"
"    }\n"
"\n"
"    function fetchData() {\n"
"        fetch(API_URL)\n"
"            .then(res => res.json())\n"
"            .then(data => updateUI(data))\n"
"            .catch(err => {\n"
"                console.error('Fetch error:', err);\n"
"                const status = document.getElementById('status');\n"
"                status.textContent = 'Disconnected';\n"
"                status.classList.remove('connected');\n"
"            });\n"
"    }\n"
"\n"
"    // Initial fetch\n"
"    fetchData();\n"
"\n"
"    // Periodic refresh\n"
"    setInterval(fetchData, REFRESH_INTERVAL);\n"
"})();\n";

/* File lookup table */
typedef struct {
    const char *path;
    const char *content;
    size_t length;
    const char *content_type;
} static_file_t;

static const static_file_t FILES[] = {
    {"/", INDEX_HTML, sizeof(INDEX_HTML) - 1, "text/html"},
    {"/index.html", INDEX_HTML, sizeof(INDEX_HTML) - 1, "text/html"},
    {"/style.css", STYLE_CSS, sizeof(STYLE_CSS) - 1, "text/css"},
    {"/app.js", APP_JS, sizeof(APP_JS) - 1, "application/javascript"},
    {NULL, NULL, 0, NULL}
};

void static_files_handler(const http_request_t *req, http_response_t *resp) {
    for (const static_file_t *f = FILES; f->path != NULL; f++) {
        if (strcmp(req->path, f->path) == 0) {
            resp->body = f->content;
            resp->body_len = f->length;
            resp->content_type = f->content_type;
            resp->status_code = 200;
            return;
        }
    }
    
    resp->body = "Not Found";
    resp->body_len = 9;
    resp->content_type = "text/plain";
    resp->status_code = 404;
}
